ALTER TABLE view_history ADD COLUMN IF NOT EXISTS viewed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE view_history ADD COLUMN IF NOT EXISTS stopped_at_minute INTEGER;

ALTER TABLE view_history ALTER COLUMN user_id TYPE VARCHAR(255) USING user_id::VARCHAR;
